apiVersion: 1
datasources:
  - name: Graphite
    type: graphite
    access: proxy
    orgId: 1
    url: 'http://graphite:8080'
    isDefault: true
    editable: true
    jsonData:
      graphiteVersion: '1.1'
    version: 1
