{
 "title": "k6",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "# [k6 Metrics Documentation](https://k6.io/docs/using-k6/metrics/)"
   },
   "targets": [
    {}
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Virtual Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "target": "stats.gauges.k6.vus" }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "target": "stats.k6.http_reqs" }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "target": "stats.k6.http_req_failed" }
   ]
  },
  {
   "title": "Request Waiting (median)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "stats.timers.k6.http_req_waiting.median"
    }
   ]
  },
  {
   "title": "Request Connecting (mean)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "stats.timers.k6.http_req_connecting.mean"
    }
   ]
  },
  {
   "title": "Bytes Received (mean)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "stats.k6.data_received" }
   ]
  },
  {
   "title": "Bytes Sent (mean)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "stats.k6.data_sent" }
   ]
  },
  {
   "title": "Response Code Counts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "stats.k6.check.*.pass" }
   ]
  },
  { "title": "Request Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Request Duration (mean)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "stats.timers.k6.http_req_duration.mean"
    }
   ]
  },
  {
   "title": "Request Duration (max)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "stats.timers.k6.http_req_duration.mean"
    }
   ]
  },
  {
   "title": "Request Duration (lower)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "stats.timers.k6.http_req_duration.lower"
    }
   ]
  },
  {
   "title": "Request Duration (95 percentile)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "nPercentile(stats.timers.k6.http_req_duration.mean, 95)"
    }
   ]
  },
  {
   "title": "Request Duration Overtime",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "target": "stats.timers.k6.http_req_duration.median"
    }
   ]
  }
 ]
}